// All visible page copy, both languages. Keys map to data-i18n attributes.
export const strings = {
  en: {
    heroKicker: 'Sparklingwill presents',
    heroTagline: 'Your photos, painted into a moment.',
    heroSub: 'Upload a photo or two. Our AI studies their colors, then paints you back a moment worth keeping.',
    heroCta: 'Get it on Google Play',
    heroIosCta: 'Download on the App Store',
    installBody: 'Get the app — your credits work everywhere.',
    installCta: 'Install',
    installDismiss: 'Dismiss',
    heroWebCta: 'Try it in your browser',
    footerWebApp: 'Web app',
    inputsLabel: 'your photos',
    arrowLabel: 'drawn from their colors',
    resultLabel: 'generated by AI',
    motionPlay: 'Play',
    motionPause: 'Pause',
    howTitle: 'How it works',
    step1Title: 'Share a photo',
    step1Body: 'Pick one or two photos of you — or anyone you love.',
    step2Title: 'Choose a style',
    step2Body: 'Fourteen styles, from neon nights to vintage film.',
    step3Title: 'Pull the crank',
    step3Body: 'A polaroid slides out — your moment, painted.',
    galleryTitle: 'Styles',
    gallerySub: '14 styles to choose from',
    tplPolaroid: 'Polaroid',
    tplMystic: 'Mystic',
    tplAcademy: 'Academy',
    tplVintage: 'Vintage',
    tplQipao: 'Qipao',
    tplForest: 'Forest',
    tplSunset: 'Sunset',
    tplSnow: 'Snow',
    tplNeon: 'Neon',
    tplPaparazzi: 'Paparazzi',
    tplCamellia: 'Camellia',
    tplTomato: 'Tomato',
    tplMohair: 'Mohair',
    tplCasual: 'Casual',
    aboutTitle: 'About Sparklingwill',
    aboutBody: 'Curate the beauty of simplicity.',
    footer: '© 2026 Sparklingwill. All rights reserved.',
    support: 'Support',
    privacy: 'Privacy Policy',
    deleteAccount: 'Delete account & data',
  },
  zh: {
    heroKicker: 'Sparklingwill 出品',
    heroTagline: '一拍，一世界。',
    heroSub: '上传一两张照片，AI 读懂它们的色彩，为你绘出值得珍藏的一刻。',
    heroCta: '在 Google Play 获取',
    heroIosCta: '在 App Store 下载',
    installBody: '下载应用——积分全平台通用。',
    installCta: '安装',
    installDismiss: '关闭',
    heroWebCta: '在浏览器中体验',
    footerWebApp: '网页版',
    inputsLabel: '你的照片',
    arrowLabel: '取其色，绘其形',
    resultLabel: 'AI 生成',
    motionPlay: '播放',
    motionPause: '暂停',
    howTitle: '如何使用',
    step1Title: '上传照片',
    step1Body: '选择一两张你或所爱之人的照片。',
    step2Title: '挑选风格',
    step2Body: '十四种风格，从霓虹夜色到复古胶片。',
    step3Title: '转动手柄',
    step3Body: '一张拍立得缓缓滑出——属于你的一刻。',
    galleryTitle: '风格',
    gallerySub: '14 种风格，任你挑选',
    tplPolaroid: '拍立得',
    tplMystic: '迷雾',
    tplAcademy: '学院',
    tplVintage: '复古',
    tplQipao: '旗袍',
    tplForest: '林间',
    tplSunset: '夕照',
    tplSnow: '落雪',
    tplNeon: '霓虹',
    tplPaparazzi: '街拍',
    tplCamellia: '山茶',
    tplTomato: '番茄',
    tplMohair: '马海毛',
    tplCasual: '随拍',
    aboutTitle: '关于 Sparklingwill',
    aboutBody: '采撷简约之美。',
    footer: '© 2026 Sparklingwill 版权所有',
    support: '支持',
    privacy: '隐私政策',
    deleteAccount: '删除账号与数据',
  },
  es: {
    heroKicker: 'Sparklingwill presenta',
    heroTagline: 'Tus fotos, pintadas en un instante.',
    heroSub: 'Sube una o dos fotos. Nuestra IA estudia sus colores y te devuelve un instante digno de guardar.',
    heroCta: 'Descárgala en Google Play',
    heroIosCta: 'Descárgala en la App Store',
    installBody: 'Descarga la app — tus créditos funcionan en todas partes.',
    installCta: 'Instalar',
    installDismiss: 'Cerrar',
    heroWebCta: 'Pruébala en tu navegador',
    footerWebApp: 'Versión web',
    inputsLabel: 'tus fotos',
    arrowLabel: 'a partir de sus colores',
    resultLabel: 'generado por IA',
    motionPlay: 'Reproducir',
    motionPause: 'Pausar',
    howTitle: 'Cómo funciona',
    step1Title: 'Comparte una foto',
    step1Body: 'Elige una o dos fotos tuyas — o de quien tú quieras.',
    step2Title: 'Elige un estilo',
    step2Body: 'Catorce estilos, de noches de neón a película vintage.',
    step3Title: 'Gira la manivela',
    step3Body: 'Sale una polaroid — tu instante, pintado.',
    galleryTitle: 'Estilos',
    gallerySub: '14 estilos para elegir',
    tplPolaroid: 'Polaroid',
    tplMystic: 'Místico',
    tplAcademy: 'Academia',
    tplVintage: 'Vintage',
    tplQipao: 'Qipao',
    tplForest: 'Bosque',
    tplSunset: 'Atardecer',
    tplSnow: 'Nieve',
    tplNeon: 'Neón',
    tplPaparazzi: 'Paparazzi',
    tplCamellia: 'Camelia',
    tplTomato: 'Tomate',
    tplMohair: 'Mohair',
    tplCasual: 'Casual',
    aboutTitle: 'Sobre Sparklingwill',
    aboutBody: 'Cuidar la belleza de lo simple.',
    footer: '© 2026 Sparklingwill. Todos los derechos reservados.',
    support: 'Soporte',
    privacy: 'Política de Privacidad',
    deleteAccount: 'Eliminar cuenta y datos',
  },
};

// The switcher lists every language in its own name, so a reader can find
// theirs without already reading the current one.
export const LANGUAGES = [
  { code: 'en', label: 'English', htmlLang: 'en' },
  { code: 'zh', label: '中文', htmlLang: 'zh-CN' },
  { code: 'es', label: 'Español', htmlLang: 'es' },
];

const STORAGE_KEY = 'sw-lang';
let current = 'en';

export function currentLang() {
  return current;
}

function apply(lang) {
  const meta = LANGUAGES.find((l) => l.code === lang) ?? LANGUAGES[0];
  current = meta.code;
  const dict = strings[current];
  document.documentElement.lang = meta.htmlLang;
  // Only Chinese needs the CJK face; the Latin serif already covers Spanish.
  document.body.classList.toggle('lang-zh', current === 'zh');
  document.querySelectorAll('[data-i18n]').forEach((el) => {
    const t = dict[el.dataset.i18n];
    if (t) el.textContent = t;
  });
  const label = document.getElementById('lang-current');
  if (label) label.textContent = meta.label;
  document.querySelectorAll('#lang-list [data-lang]').forEach((btn) => {
    btn.setAttribute('aria-checked', String(btn.dataset.lang === current));
  });
  // Labels whose text depends on runtime state (the paint toggle) can't use
  // data-i18n, so let them relabel themselves.
  document.dispatchEvent(new CustomEvent('sw:langchange', { detail: { lang: current } }));
}

export function t(key) {
  return strings[current][key];
}

function resolveInitial() {
  let saved = null;
  try { saved = localStorage.getItem(STORAGE_KEY); } catch { /* storage blocked */ }
  if (LANGUAGES.some((l) => l.code === saved)) return saved;
  const nav = (navigator.language || '').toLowerCase();
  return LANGUAGES.find((l) => nav.startsWith(l.code))?.code ?? 'en';
}

function initMenu() {
  const button = document.getElementById('lang-button');
  const list = document.getElementById('lang-list');
  if (!button || !list) return;

  // Built from LANGUAGES so adding a language is a one-line change here.
  list.replaceChildren(...LANGUAGES.map((l) => {
    const li = document.createElement('li');
    li.setAttribute('role', 'none');
    const item = document.createElement('button');
    item.type = 'button';
    item.setAttribute('role', 'menuitemradio');
    item.setAttribute('aria-checked', String(l.code === current));
    item.dataset.lang = l.code;
    item.textContent = l.label;
    item.addEventListener('click', () => {
      try { localStorage.setItem(STORAGE_KEY, l.code); } catch { /* storage blocked */ }
      apply(l.code);
      close(true);
    });
    li.append(item);
    return li;
  }));

  const items = () => [...list.querySelectorAll('[data-lang]')];
  const isOpen = () => !list.hidden;

  function open() {
    list.hidden = false;
    button.setAttribute('aria-expanded', 'true');
    (items().find((i) => i.dataset.lang === current) ?? items()[0])?.focus();
  }
  function close(refocus) {
    list.hidden = true;
    button.setAttribute('aria-expanded', 'false');
    if (refocus) button.focus();
  }

  button.addEventListener('click', () => (isOpen() ? close(false) : open()));

  // Arrow keys move within the menu, Escape closes it, Tab lets focus leave.
  list.addEventListener('keydown', (e) => {
    const all = items();
    const i = all.indexOf(document.activeElement);
    if (e.key === 'Escape') { e.preventDefault(); close(true); }
    else if (e.key === 'ArrowDown') { e.preventDefault(); all[(i + 1) % all.length].focus(); }
    else if (e.key === 'ArrowUp') { e.preventDefault(); all[(i - 1 + all.length) % all.length].focus(); }
    else if (e.key === 'Home') { e.preventDefault(); all[0].focus(); }
    else if (e.key === 'End') { e.preventDefault(); all[all.length - 1].focus(); }
    else if (e.key === 'Tab') { close(false); }
  });
  button.addEventListener('keydown', (e) => {
    if (e.key === 'ArrowDown' || e.key === 'ArrowUp') { e.preventDefault(); open(); }
  });
  document.addEventListener('click', (e) => {
    if (isOpen() && !list.contains(e.target) && !button.contains(e.target)) close(false);
  });
}

export function initI18n() {
  current = resolveInitial();
  initMenu();
  apply(current);
}
