// All visible page copy, both languages. Keys map to data-i18n attributes.
export const strings = {
  en: {
    heroKicker: 'Sparklingwill presents',
    heroTagline: 'Your photos, painted into a moment.',
    heroSub: 'Upload a photo or two. Our AI studies their colors, then paints you back a moment worth keeping.',
    heroCta: 'Coming soon to Google Play',
    inputsLabel: 'your photos',
    arrowLabel: 'drawn from their colors',
    resultLabel: 'generated by AI',
    howTitle: 'How it works',
    step1Title: 'Share a photo',
    step1Body: 'Pick one or two photos of you — or anyone you love.',
    step2Title: 'Choose a style',
    step2Body: 'Fourteen styles, from neon nights to vintage film.',
    step3Title: 'Pull the crank',
    step3Body: 'A polaroid slides out — your moment, painted.',
    galleryTitle: 'Styles',
    gallerySub: '14 styles to choose from',
    tplPolaroid: 'Polaroid',
    tplMystic: 'Mystic',
    tplAcademy: 'Academy',
    tplVintage: 'Vintage',
    tplQipao: 'Qipao',
    tplForest: 'Forest',
    tplSunset: 'Sunset',
    tplSnow: 'Snow',
    tplNeon: 'Neon',
    tplPaparazzi: 'Paparazzi',
    tplCamellia: 'Camellia',
    tplTomato: 'Tomato',
    tplMohair: 'Mohair',
    tplCasual: 'Casual',
    aboutTitle: 'About Sparklingwill',
    aboutBody: 'Curate the beauty of simplicity.',
    footer: '© 2026 Sparklingwill. All rights reserved.',
    privacy: 'Privacy Policy',
    deleteAccount: 'Delete account & data',
  },
  zh: {
    heroKicker: 'Sparklingwill 出品',
    heroTagline: '一拍，一世界。',
    heroSub: '上传一两张照片，AI 读懂它们的色彩，为你绘出值得珍藏的一刻。',
    heroCta: '即将登陆 Google Play',
    inputsLabel: '你的照片',
    arrowLabel: '取其色，绘其形',
    resultLabel: 'AI 生成',
    howTitle: '如何使用',
    step1Title: '上传照片',
    step1Body: '选择一两张你或所爱之人的照片。',
    step2Title: '挑选风格',
    step2Body: '十四种风格，从霓虹夜色到复古胶片。',
    step3Title: '转动手柄',
    step3Body: '一张拍立得缓缓滑出——属于你的一刻。',
    galleryTitle: '风格',
    gallerySub: '14 种风格，任你挑选',
    tplPolaroid: '拍立得',
    tplMystic: '迷雾',
    tplAcademy: '学院',
    tplVintage: '复古',
    tplQipao: '旗袍',
    tplForest: '林间',
    tplSunset: '夕照',
    tplSnow: '落雪',
    tplNeon: '霓虹',
    tplPaparazzi: '街拍',
    tplCamellia: '山茶',
    tplTomato: '番茄',
    tplMohair: '马海毛',
    tplCasual: '随拍',
    aboutTitle: '关于 Sparklingwill',
    aboutBody: '采撷简约之美。',
    footer: '© 2026 Sparklingwill 版权所有',
    privacy: '隐私政策',
    deleteAccount: '删除账号与数据',
  },
};

function apply(lang) {
  const dict = strings[lang];
  document.documentElement.lang = lang === 'zh' ? 'zh-CN' : 'en';
  document.body.classList.toggle('lang-zh', lang === 'zh');
  document.querySelectorAll('[data-i18n]').forEach((el) => {
    const t = dict[el.dataset.i18n];
    if (t) el.textContent = t;
  });
  const toggle = document.getElementById('lang-toggle');
  if (toggle) toggle.textContent = lang === 'zh' ? 'EN' : '中文';
}

export function initI18n() {
  const saved = localStorage.getItem('sw-lang');
  const lang = saved === 'en' || saved === 'zh'
    ? saved
    : (navigator.language || '').toLowerCase().startsWith('zh') ? 'zh' : 'en';
  apply(lang);
  document.getElementById('lang-toggle')?.addEventListener('click', () => {
    const next = document.documentElement.lang.startsWith('zh') ? 'en' : 'zh';
    localStorage.setItem('sw-lang', next);
    apply(next);
  });
}
